version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis (includes gosimple)
    - unused        # Check for unused constants, variables, functions and types
    - misspell      # Check for misspelled words
    - gocritic      # Comprehensive Go code checker
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - revive        # Fast, configurable, extensible linter
    - unconvert     # Unnecessary type conversions
    - prealloc      # Find slice declarations that could potentially be preallocated
    - nilerr        # Finds code that returns nil even if it checks that error is not nil
    - copyloopvar   # Detects places where loop variables are copied

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Disabled: minimal performance benefit, high maintenance cost
      settings:
        shadow:
          strict: true

    gocyclo:
      min-complexity: 15

    dupl:
      threshold: 100

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint

    misspell:
      locale: US

    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: superfluous-else
        - name: unreachable-code

  exclusions:
    generated: lax
    paths:
      - vendor

    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - dupl
          - gosec

      # Allow unused writes in tests for complete struct initialization
      - path: _test\.go
        text: "unusedwrite"

      # Exclude HTML templates in reporter from dupl check
      - path: internal/reporter/reporter\.go
        linters:
          - dupl
          - gocyclo

      # Exclude main.go from dupl and gocyclo - intentional warning boxes and CLI complexity
      - path: cmd/lobster/main\.go
        linters:
          - dupl
          - gocyclo

      # Exclude robots parser from gocyclo - complex RFC compliance logic
      - path: internal/robots/robots\.go
        linters:
          - gocyclo

      # Exclude tester from shadow, gocritic, and gocyclo - intentional error handling patterns
      - path: internal/tester/tester\.go
        linters:
          - govet
          - gocyclo
        text: "shadow:|cyclomatic complexity"

      - path: internal/tester/tester\.go
        linters:
          - gocritic
        text: "hugeParam"

      # Exclude tests from gocritic nesting suggestions
      - path: _test\.go
        linters:
          - gocritic
        text: "nestingReduce"

      # Allow dot imports
      - text: "should not use dot imports"
        linters:
          - revive

      # Exclude hugeParam for config structs - intentional pass by value for immutability
      - text: "hugeParam"
        linters:
          - gocritic

      # Exclude emptyStringTest - valid code patterns in tests
      - path: _test\.go
        text: "emptyStringTest"
        linters:
          - gocritic

      # Exclude unnamedResult in tests - helper functions
      - path: _test\.go
        text: "unnamedResult"
        linters:
          - gocritic

      # Exclude auth.go from gocyclo - complex but necessary auth logic
      - path: internal/cli/auth\.go
        linters:
          - gocyclo

      # Exclude url_validator.go from gocyclo and shadow - complex IP validation
      - path: internal/util/url_validator\.go
        linters:
          - gocyclo
          - govet

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
