run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis (includes gosimple)
    - unused        # Check for unused constants, variables, functions and types
    - misspell      # Check for misspelled words
    - gocritic      # Comprehensive Go code checker
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - revive        # Fast, configurable, extensible linter
    - unconvert     # Unnecessary type conversions
    - prealloc      # Find slice declarations that could potentially be preallocated
    - nilerr        # Finds code that returns nil even if it checks that error is not nil
    - copyloopvar   # Detects places where loop variables are copied

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Disabled: minimal performance benefit, high maintenance cost
    settings:
      shadow:
        strict: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: unreachable-code

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec

    # Allow unused writes in tests for complete struct initialization
    - path: _test\.go
      text: "unusedwrite"

    # Exclude HTML templates in reporter from dupl check
    - path: internal/reporter/reporter\.go
      linters:
        - dupl
        - gocyclo

    # Allow init functions
    - text: "should not use dot imports"
      linters:
        - revive
